version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env.docker
    depends_on:
      - db
    restart: on-failure
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "datafetcher"
      MYSQL_USER: ""
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: